// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw3BRy8bi_cU-8CGsocLlTPzs4DBF8_Co',
    appId: '1:573414405818:web:ebe6da262456868b4e3483',
    messagingSenderId: '573414405818',
    projectId: 'bookwise-14f7f',
    authDomain: 'bookwise-14f7f.firebaseapp.com',
    storageBucket: 'bookwise-14f7f.appspot.com',
    measurementId: 'G-CVPZGV9NMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7_-0Gls3ro0DR1kys-uAyAvzfBCcumdQ',
    appId: '1:573414405818:android:2c8f91355ca489da4e3483',
    messagingSenderId: '573414405818',
    projectId: 'bookwise-14f7f',
    storageBucket: 'bookwise-14f7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoWe4daNG0uiAieUwFuM-wSnlNk1-l6RQ',
    appId: '1:573414405818:ios:fa82001ceead99764e3483',
    messagingSenderId: '573414405818',
    projectId: 'bookwise-14f7f',
    storageBucket: 'bookwise-14f7f.appspot.com',
    iosBundleId: 'com.example.bookwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoWe4daNG0uiAieUwFuM-wSnlNk1-l6RQ',
    appId: '1:573414405818:ios:8a1df6f0ddcf5e174e3483',
    messagingSenderId: '573414405818',
    projectId: 'bookwise-14f7f',
    storageBucket: 'bookwise-14f7f.appspot.com',
    iosBundleId: 'com.example.bookwise.RunnerTests',
  );
}
